version: '3.1'

services:
  # mongodb server
  mongo_rc:
    image: mongo:3.6.5-jessie
    restart: always
    ports:
      - '27017:27017'
    # networks:
    #   - inkbook
    volumes:
      - 'mongo_rc_volume:/data/db'

  # api server
  api_rc:
    build:
      context: ./api
      dockerfile: rc.Dockerfile
    image: syncplayer-api:rc
    # networks:
    #   - inkbook
    depends_on:
      - mongo_rc
  
  # web app
  app_rc:
    build:
      context: ./app
      dockerfile: rc.Dockerfile
    image: syncplayer-app:rc
    # networks:
    #   - inkbook
    depends_on:
      - api_rc

  # nginx http proxy server
  proxy_rc:
    build:
      context: ./nginx
      dockerfile: rc.Dockerfile
    image: syncplayer-proxy:rc
    ports:
      - '80:80'
      # - '443:443'
    # volumes:
    #   - '/etc/ssl/private/inkbook.io.key:/etc/ssl/private/inkbook.io.key:ro'
    #   - '/etc/ssl/certs/inkbook.io-ssl-bundle.crt:/etc/ssl/certs/inkbook.io-ssl-bundle.crt:ro'
    # networks:
    #   - inkbook
    depends_on:
      - api_rc
      - app_rc

volumes:
  # used by mongodb
  mongo_rc_volume:

# networks:
#   inkbook:
#     external: true
